version: '3.9'

services:
  automobile-app:
    build: .
    restart: always
    depends_on:
      - vehicle-db
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: jdbc:postgresql://vehicle-db:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      JWT_SECRET: ${JWT_SECRET}
      GEOCODING_API_KEY: ${GEOCODING_API_KEY}
      GEOCODING_API_URL: ${GEOCODING_API_URL}
    volumes:
      - ./logs:/app/logs

  vehicle-db:
    image: postgis/postgis:17-3.5-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - vehicle-db-data:/var/lib/postgresql/data

volumes:
  vehicle-db-data:
