spring:
  thymeleaf:
    cache: false
  application:
    name: "AutomobileApp"
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5434/postgres}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: "classpath:changelog/changelog-master.xml"
    enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30
