spring:
  shell:
    interactive:
      enabled: true
  thymeleaf:
    cache: false
  application:
    name: "AutomobileApp"
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5434/postgres}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  liquibase:
    change-log: "classpath:changelog/changelog-master.xml"
    enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30
external:
  geocoding:
    url: ${GEOCODING_API_URL}
    api-key: ${GEOCODING_API_KEY}
    timeout: 5000
    retry:
      max-attempts: 3
      backoff: 1000
